### PR TITLE
Updated code to newer android compatibles, Updated error 9-patch

### PR DESCRIPTION
**Pull request by OmarShoaib**
Hi Ali, 

First of all, this repository of yours is literally amazing and helpful. While using this library I encountered an issue in which error image you used messes up the UI as the field gets bigger because of this image on error prompt. So I've updated that image plus upgraded your project to run on newer android versions.

It'll be really grateful to you if you could accept this pull request.

Please let me know if you want to ask anything. I'm just a message away.

Thanks.

### CODE REVIEW

**Comment by AliAzaz** [comment]
Thanks a lot, @OmarShoaib for contributing to this library and your support in giving back to the community. Shoaib, it has been quite some time that I wasn't maintaining this library due to that you people are facing issues. 
@OmarShoaib you mentioned that you are experiencing some UI distortion issues, can you please share any screenshots for better understanding?

**Comment by OmarShoaib** [comment]
Screenshot_20231002-112925_ITRIPP 1

For your reference.

**Comment by AliAzaz** [comment]
@OmarShoaib I got it and thanks a lot for pointing out this issue. Can you please remove **.idea** files from your PR so, I can merge it?

**Comment by AliAzaz** [comment]
I am going this PR and will generate the release in a while

**Review by AliAzaz — APPROVED** [review]
.idea files are not to be added while creating PR in any project because these files are generated by Android Studio where it is installed.

**Pull request merged**
